### ISSUE TITLE
您好，请问下这是什么问题

### ISSUE THREAD

**Issue by KirisakiAria** [a3165458/Babylon#2]
![image](https://github.com/a3165458/Babylon/assets/20788476/b6c8faa2-accf-4f94-8327-55e19af10906)
用的谷歌云跑的，但是显示连接不上peer address，昨天就一直这个问题，重新开了实例跑了好几次，然后今天挂了一天了还是这样。
babylond命令也无效，command not found

![image](https://github.com/a3165458/Babylon/assets/20788476/b17b4211-3891-4256-a66c-d4741ada6e5e)
看了下监控，IO是一直拉满的，这也导致了我ssh卡的一逼

望大佬赐教，感谢！

**Comment by a3165458** [comment]
执行这步:echo "export PATH=$PATH:/usr/local/go/bin:$HOME/go/bin" >> $HOME/.bash_profile
source $HOME/.bash_profile

peers 的问题，你得去polkachu 更新下P2P节点了:https://polkachu.com/testnets/babylon/peers

**Comment by KirisakiAria** [comment]
问题已经解决，太感谢了！
