### ISSUE TITLE
你好，发送创建验证者交易报错这是什么问题呢？

### ISSUE THREAD

**Issue by vicnoah** [a3165458/Babylon#3]
```
# 发送创建验证者交易信息
babylond tx checkpointing create-validator ~/validator.json \
    --chain-id="bbn-test-3" \
    --gas="auto" \
    --gas-adjustment="1.5" \
    --gas-prices="0.025ubbn" \
    --from=wallet
```
执行后错误提示部分
10:11PM ERR failure when running app err="failed to convert address field to address: wallet.info: key not found [cosmos/cosmos-sdk@v0.50.4-0.20240126152601-c4a2fe2b8987/crypto/keyring/keyring.go:538]"

**Comment by a3165458** [comment]
钱包名是不是改过，检查下 ，from 后面跟随的是你的钱包名

**Comment by vicnoah** [comment]
> 钱包名是不是改过，检查下 ，from 后面跟随的是你的钱包名

钱包名称看起来是对的，不知道什么原因
![image](https://github.com/a3165458/Babylon/assets/20820831/98fe2ca4-1def-46db-9a69-51a2dd6ea9dd)

**Comment by vicnoah** [comment]
> 钱包名是不是改过，检查下 ，from 后面跟随的是你的钱包名

我这看起来名称应该是对的吧，我反复核对过。
![image](https://github.com/a3165458/Babylon/assets/20820831/79cc5826-1528-444f-a325-8e4b3a5ba3f5)

**Comment by a3165458** [comment]
用babylond query bank balances bbn地址，查下水够吗，创建验证者的质押数量不够，也是这个报错

**Comment by vicnoah** [comment]
> 用babylond query bank balances bbn地址，查下水够吗，创建验证者的质押数量不够，也是这个报错

这个命令好像也会报错，看起来就像是钱包地址的问题。不是太明白
![image](https://github.com/a3165458/Babylon/assets/20820831/802e8015-2953-4ae4-9d97-2dc4396bf3ea)

**Comment by vicnoah** [comment]
```
ubuntu@VM-0-2-ubuntu:~$ babylond query bank balances bbn
Error: invalid argument "bbn" for "--0" flag: invalid account address or key name: decoding bech32 failed: invalid bech32 string length 3
3:31PM ERR failure when running app err="invalid argument \"bbn\" for \"--0\" flag: invalid account address or key name: decoding bech32 failed: invalid bech32 string length 3"
```

**Comment by vicnoah** [comment]
> 用babylond query bank balances bbn地址，查下水够吗，创建验证者的质押数量不够，也是这个报错

执行后的显示结果，就是没水吗？我钱包显示有6bbn
ubuntu@VM-0-2-ubuntu:~$ babylond query bank balances bbn195tndx20kv437qsqdf8k7wm7lgrm63dwjhxnhm
balances: []
pagination: {}

钱包显示是有余额的
![image](https://github.com/a3165458/Babylon/assets/20820831/ccd0cd51-abee-418f-b5d9-ec959224377d)

![image](https://github.com/a3165458/Babylon/assets/20820831/7c021f22-f686-43a6-890e-d9b86173ea90)

**Comment by a3165458** [comment]
以CLI为准，CLI显示空白，那就是还没到账

**Comment by vicnoah** [comment]
> 以CLI为准，CLI显示空白，那就是还没到账

那明白了，谢谢。等到账了我再试试
